### ISSUE TITLE
:sparkles: Feature Suggestion: As a palm-dbt user, I want the ability to select a dbt version

### ISSUE THREAD

**Issue by emekdahl** [palmetto/palm-dbt#34]
**Context**
When containerizing dbt, I want the ability to select the dbt version I am using

**Is your feature request related to a problem? Please describe.**
When I run containerize, it defaults to 0.21.0. I wouldn't catch this unless I knew to double-check the docker file.

**Describe the solution you'd like**
Prompt the user to enter (or at least confirm) the dbt version (if the package is getting it from somewhere else).

**Describe alternatives you've considered**

**Additional context**

**Is there an existing feature request for this?**
 * [ ]  I have searched the existing issues

**Comment by emekdahl-palmetto** [comment]
Closed in v0.1.2
