### ISSUE TITLE
:sparkles: Support for dbt-core v1.0.x

### ISSUE THREAD

**Issue by jakeberesford-palmetto** [palmetto/palm-dbt#43]
**Context**
dbt just released v1.0! We want to support the latest version

**Is your feature request related to a problem? Please describe.**
Improvement - support the latest and greatest!

**Describe the solution you'd like**
* Update containerize version support to include v1.0
* Implement any necessary changes/improvements to make the most of dbt v1.0!

**Describe alternatives you've considered**
* There is no alternative, we need to do this!

**Is there an existing feature request for this?**
 * [x]  I have searched the existing issues

**Comment by emekdahl-palmetto** [comment]
Note: the passing build args to docker was key to the resolution of this in our own stack.

**Comment by mariahjrogers** [comment]
Resolved by #70
