### ISSUE TITLE
:lady_beetle: dbt v1.5 deprecated/renamed `dbt_state_artifact_path` and `dbt_defer_to_state` env vars

### ISSUE THREAD

**Issue by mariahjrogers** [palmetto/palm-dbt#88]
**Describe the bug**
dbt 1.5 has renamed the environment variables for defer and state artifact usage. This means palm throws warnings on every dbt command that utilizes state or run_results

**Your environment**
- `palm` version: 2.5.3
- OS: Mac OS
- Docker version:
- Other dependencies & versions: dbt V1.5.2

**How to reproduce**
Upgrade to dbt 1.5+ and run palm

**Expected behavior**
Palm doesn't rely on deprecated features and runs without verbose warnings

**Actual behavior**
Every palm command run produces warnings from dbt

**Screenshots**
None

**Additional context**
N/A

**Comment by jakeberesford-palmetto** [comment]
Thanks for the bug report. Can you share the output of the warning that you are seeing?

**Comment by mariahjrogers** [comment]
![Screenshot 2023-09-06 at 3 09 19 PM](https://github.com/palmetto/palm-dbt/assets/85898387/07f578a8-01f0-4d1f-9385-eb6f506db8c6)

**Comment by jakeberesford-palmetto** [comment]
This is absolutely something we want to address. We need to implement dbt version detection in the plugin as part of this work. Currently, we don't have a good way to do that.
